---
title: "Methods and Results - Rough"
author: "Farhan Majumder"
date: "December 4, 2017"
output: html_document
---

# Methods 

## Dataset
Data was obtained from the “Marine predator and prey body sizes”, created by Barnes et al.; joint venture generated by 17 different international institutions. As such, we have data from global locations on organisms and their environment. We focused on data on environmental variables to see which ones suggest a correlation with predator mass and prey mass. Our variables of interest were selected to be: specific habitat location and feeding behaviour. 

## Graph
Importing the dataset into R, we used the package ggplot2 to visualize the patterns and trend in the aforementioned variables. Three graphs were generated from the data. The first figure compares predator mass and prey mass. The second figure is a map graph representing the locations of all the 27 international marine locations where our data was obtained. Using the facet feature of ggplot2, the third figure visualized the affect of feeding behaviour and the specific location on the relationship of predator-prey mass ratios.

## Models
To determine which variables are affecting the slope of predator-prey mass relations, we generated several models. (using glm; and lmr; and mn <- talk about these later). Every model assumes that the predator mass are the independent variable, and the prey mass are the dependent variable. The first model was a control model; assuming that there was nothing affecting the interaction of predator-prey mass. The second model incorporates the effect of specific habitat on the intercept and slope of the predator-prey mass ratio. Fourth model incorporates the effect of feeding behaviour on the intercept and slope of the predator-prey mass ratio.  The third model incorporates the additive effect of both specific habitat and feeding behaviour. The sixth model incorporates the mixed effect of habitat on feeding behaviour in the predator-prey mass interaction. The seventh model incorporates the mixed effect of feeding behaviour in the mass interaction. The last model incorporates for “everything” (<- need more details).  


# Results: 

## Graphs
The first graph shows a positive correlation between the log of predator mass and the log of prey mass; visualized via a linear regression line. As the dataset indicated, prey mass was determined off predator mass; ergo prey mass is the dependent variable. 

Second graph is a map-graph representing the locations of the sample locations (MORE TO COME) 

Third graph is the one that details how feeding behaviour and specific habitat affect the interaction of predator-prey mass. We can generalize the feeding behaviours of the predators into two categories: specialist feeders (the predators categorized as piscivorous, insectivorous, and herbivorous) and generalist feeders (categorized only has predacious). All the graphs under the specialist feeders showed a mild to strong positive correlation between predator and prey mass. 
*In the piscivorous column, of the ten total plots, 8 of them show a positive correlation, 2 of them show neutral correlation
*In the planktivourous column, of the six plots that have a linear regression, 5 of them are positive in correlation, the last one shows a neutral correlation.
On the other hand, within the graphs under generalist feeders, there were a variety of trends; some showed positive correlations, but also some interactions were neutral and even negative in correlation. 
*There are 12 plots in the column under predacious. 6 of the plots show an indication of positive trend, 5 show a neutral correlation, and one show a negative correlation. 



#Results version two: 

With accordance to the abstract provided by the authors of the dataset, we were able to confirm their finding that there was a relationship between the log of predator and prey mass, visualized by a linear regression. In trying to understand the causal effects of the interaction, the previous plot was facetted to display the different specific habitats from where the data was sampled. We were able to note that there was a clear arrangement of the various habitats on the plot; different sizes of organisms were found in the different habitats.   

To rationalize why there is a division of predator sizes between the different habitats, a potential hypothesis based on available data is that there is a difference of available prey at the various locations. Feeding behaviour would dictate what types of prey the predators consumed. The second graph visualizes the effects of both variables on the interaction of predator and prey biomass. Three feeding behaviours were chosen: piscivorous, planktivorous, and predacious; categorizing the former two as specialist-feeders as they only eat one type of prey (fish and plankton, respectively) and the latter as a generalist-feeder as they eat different types of prey. When we focus on the feeding behaviours, there is an interesting pattern that emerges: in general, the specialist feeders – despite what specific habitat we are observing – show either a positive or a neutral interaction between predator and prey body mass. On the other hand, when looking at the predacious-feeders, there is more variance in the data; in some habitats there is a positive interaction, but some areas show a neutral interaction, and one habitat shows a negative interaction. 

The next step was to understand whether the affects of the variables were statistically significant to influence the interaction; is it the effect of one of the two variables highlighted above, or a combination of the two. To do so, several mixed-effects models were used. From the 4-or-7 (GOTTA EDIT THIS) that were completed, the most influential model pointed to a combined effect of location and feeding behaviour; this was determined through an AIC analysis done on the models. Specifically, based on the results, model 11 and model 12 appear to best explain predator-prey body size relationships in marine ecosystems. We concluded that while model 12 had more had more explanatory power, it was not significantly better than model 11 (AIC was less than 2; with a p value of 0.077). Furthermore, model 11 was significantly better than model 10 (p value was smaller than 2e-16), which instead assumes different slopes and intercepts for each feeding behaviour, plus an interaction with habitat. Ergo, the best models indicate that the slope and intercept of the predator-prey mass interaction line-of-best-fit in influenced by a combined effects of habitat and feeding interaction. 

As described above, under the chosen model, each combination of feeding behaviour and associated specific habitats influence the slopes of the predator-prey mass interactions. 

Also more to note, the model shows that compared to a 1-1 slope, almost all of the interactions show a shallower slope of less than 1. It is also interesting to note that comparing the variance of the interaction ratios, the generalist-feeders show the greatest range compared to all of them.






# Methods version three: 


Data was obtained from the *Marine predator and prey body sizes*, created by Barnes et al.; joint venture generated by 17 different international institutions. As such, we have data from global locations on organisms and their environment. We focused on data on two specific environmental variables to see which ones suggest a correlation with predator mass and prey mass. Our variables of interest were selected to be: specific habitat location and feeding behaviour. We can generalize the feeding behaviours of the predators into two categories: specialist feeders (the predators categorized as piscivorous, insectivorous, and herbivorous; they eat only one type of prey) and broad-range feeders (categorized only as predacious; they eat a variety of different types of prey). Prey mass is dependent on predator mass, as according to the dataset, predators were captured and prey data was extrapolated from gut content. Later in the data exploration, insectivorous and predacious/piscivorous data was removed as they were represented in only one habitat each (the other feeding behaviours were represented in at least 2 habitats). 

Importing the dataset into R, we used the package ggplot2 to visualize the patterns and trend in the aforementioned variables. Four graphs were generated from the data. The first figure compares predator mass and prey mass. The second figure represents the locations of all the 27 international marine locations where our data was obtained. Using the facet feature of ggplot2, the third figure visualized the affect of feeding behaviour and the specific location on the relationship of predator-prey mass relationships. The fourth graph visualizes the sample sizes of each habitat sampled.

To determine which variables are affecting the slope of predator-prey mass relations, we generated several models (linear models made based of the glm function in R and mixed-effect models based off the lmr and mn functions). Mixed-effect models were used, as we do not believe our variables of specific habitat and feeding behaviour are independent of each other; they influence each other. The goal of the models is to understand how they affect the predator-prey mass. Every model assumes that the predator mass are the independent variable, and the prey mass are the dependent variable. Also, every model assumes an effect of feeding-type and specific habitat (except the null). The first model (null) was a control model; assuming that there was nothing affecting the interaction of predator-prey mass. The second model (lm9) incorporates the effect of feeding-type on the intercept of the predator-prey mass. Third model (lm10) incorporates the effect of feeding behaviour on the intercept and slope of the predator-prey mass relationship.  The fourth model (lm11) incorporates the effect of specific habitat on the intercept and slop of the predator-prey mass relationship. The fifth model (lm 12) incorporates the additive effects of both specific habitat and feeding behaviour on the slope and intercept of the predator-prey mass relationship. An AIC and ANOVA was conducted on the models.





# Results version three: 


With accordance to the abstract provided by the authors of the dataset, we were able to confirm their finding that there was a relationship between the log of predator and prey mass, visualized by a linear regression. In trying to understand the causal effects of the interaction, the previous plot was facetted to display the different specific habitats from where the data was sampled. We were able to note that there was a clear arrangement of the various habitats on the plot; different sizes of organisms were found in the different habitats.   

To rationalize why there is a division of predator sizes between the different habitats, a potential hypothesis based on available data is that there is a difference of available prey at the various locations. Feeding behaviour would dictate what types of prey the predators consumed. The second graph visualizes the effects of both variables on the interaction of predator and prey biomass. Three feeding behaviours were chosen due to their representation in more than one habitat: piscivorous, planktivorous, and predacious; categorizing the former two as specialist-feeders as they only eat one type of prey (fish and plankton, respectively) and the latter as a broad-range-feeders as they eat different types of prey. There is an interesting pattern that emerges: in general, each plot – which is a combination of effects of the habitat of sampling and feeding behaviours of the predators in the habitat – has it’s own unique slope which visualizes the relationship of predator-prey body mass. Also we realized that there is different composition of predator feeding behaviours in each habitat; some have a few types of feeding interactions, and others are dominated by one type of feeding interaction. Before we proceeded to go into statistical modelling, we realized that not every habitat sampled had an equal representation in the data. In order to interpret further results with more clarity, it was best to understand the number or organisms sampled from each location. A tally of habitats sampled indicate that there were three areas of less than 100 individuals (Coastal Greenland, Inshore, and Nearshore Waters); these areas would have little influence in the data, whereas Pelagic had above 15,000 organisms sampled; will have heavy influence in the data. 

The next step was to understand whether the affects of the variables were statistically significant to influence the interaction; is it the effect of one of the two variables highlighted above, or a combination of the two. To do so, several mixed-effects models were used. From the 5 models that were created, the most influential model pointed to a combined effect of location and feeding behaviour: Models 11 and 12. Specifically, based on the results, model 11 and model 12 appear to best explain predator-prey body size relationships in marine ecosystems. Both of these models displayed high percentage chance to be the most likely model (lm11 weight = 0.31 and lm12 =0.69) when comparing to the rest. The next was to determine which model between the two is more preferred. We concluded that while model 12 had more had more explanatory power, it was not significantly better than model 11 (AIC was less than 2; with a p value of 0.077). Furthermore, model 11 was significantly better than model 10 (p value was smaller than 2e-16), which instead assumes different slopes and intercepts for each feeding behaviour, plus an interaction with habitat. Ergo, the best models indicate that the slope and intercept of the predator-prey mass interaction line-of-best-fit in influenced by a combined effects of habitat and feeding interaction. Model 12 is the best. 

As described above, under the chosen model, each combination of feeding behaviour and associated specific habitats influence the y-intercept and slope of the predator-prey mass interactions. In general, when we compare the three feeding behaviours, there seems to be a visible difference of the intercept, with the slope for piscivorous being the highest. 

On the other hand, despite the changes in the habitat and feeding behaviour, a majority of the results show a shallow slope for the predator-prey mass interaction, in relation to the general-trend line visualized by the black bar. Shallow slopes indicate relationships that are closer to a neutral effect, which may assume a loose correlation between predator-prey mass ratios. It is also interesting to note that comparing the variance of the interaction relationships, the broad-ration-feeders show the widest range compared to all of them. It incorporates both the lowest and highest value of slope, compared to the narrower ranges of slope data for the specialist-predators.


